# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'PonyFaces' do
  pod 'AFNetworking', '~> 2.6'
end

target 'PonyFacesTests' do

end

target 'PonyFacesUITests' do

end

